- build: examples/1-simple-DeviceNotesHelperRK
  photon: [0.7.0, 1.0.0, 1.1.1, 1.3.1, 1.4.0]
  p1: [latest]
  electron: [0.7.0, 1.0.0, 1.1.1, 1.3.1, 1.4.0]
  argon: [0.9.0, 1.1.1, 1.3.1, 1.4.0]
- build: examples/2-counter-DeviceNotesHelperRK
  photon: [latest]
  boron: [latest]
- build: examples/3-print-DeviceNotesHelperRK
  photon: [latest]
  electron: [latest]
  xenon: [latest]
